Resources:
  JenkinsInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t2.micro
      ImageId: 'ami-033b95fb8079dc481'
      SecurityGroups:
        - !Ref JenkinsSecurityGroup
      KeyName: nginxKey
      UserData:
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            sudo -i
            amazon-linux-extras install -y epel
            yum update -y 
            wget -O /etc/yum.repos.d/jenkins.repo \
                https://pkg.jenkins.io/redhat-stable/jenkins.repo
            rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
            yum update -y
            amazon-linux-extras install java-openjdk11
            yum install -y jenkins 
            systemctl start jenkins
            systemctl enable jenkins
            systemctl daemon-reload        
  JenkinsSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
Outputs:
  InstanceID:
    Description: "InstanceId of the newly created instance"
    Value: !Ref JenkinsInstance